#  NOTE
#  This configuration content will be replaced with accounts-overview-ui.yml 
#  from the central configuration management site, GitHub.
#  https://github.com/danielyhcho/javaplays-microservicedemo-config
