# Service Description
info: 
  component: Confugration Service that pulls versioned configurations from GitHub for each microservice in distributed mode.

# Configuration Service Information
spring:
  cloud:
    config:
      server:
        git:
          uri: http://github.com/danielyhcho/javaplays-microservicedemo-config
      discovery:
        enabled: true
  
# HTTP Server
server:
  port: 2222