# Service Description
info: 
  component: Confugration Service that pulls versioned configurations from GitHub for each microservice in distributed mode.

# HTTP Server
server:
  port: 1111

# Configuration Service Information
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/danielyhcho/javaplays-microservicedemo-config
          basedir: target/config