#  NOTE
#  This configuration content will be replaced with circuit-breaker-dashboard-service.yml 
#  from the central configuration management site, GitHub.
#  https://github.com/danielyhcho/javaplays-microservicedemo-config