#  NOTE
#  This configuration content will be replaced with api-service-choreographer.yml 
#  from the central configuration management site, GitHub.
#  https://github.com/danielyhcho/javaplays-microservicedemo-config