#  NOTE
#  This configuration content will be replaced with api-gateway-service.yml 
#  from the central configuration management site, GitHub.
#  https://github.com/danielyhcho/javaplays-microservicedemo-config

# Service Description
info: 
  component: api-gateway-service using Zuul server

# HTTP Server port binding configuration
server:
  port: 3333

# Roouting configuration
zuul:
  retryable:  true
  prefix: /api
  # ignore all incoming requests except pattern defined in 'routes' section
  ignoredServices: '*'
  # regiser authorized route requests
  routes:
    # api_gateway_server/api/configurationrepo request routes to the github defined below
    configuration_repository:
      path: /configurationrepo/**
      url: http://github.com/danielyhcho/javaplays-microservicedemo-config
    # api_gateway_server/api/configuration request routes to the configuration server for individual microservice's configuration distribution
    configuration_service:
      path: /configuration/**
      serviceId: configuration-service
    # api_gateway_server/api/discovery request routes to the Eureka service registry and discovery monitoring site
    discovery_service:
      path: /discovery/**
      #url: ${vcap.services.discovery-service.credentials.uri:http://localhost:1111/}
      url: http://discoveryservice-danielcho.mybluemix.net
    # api_gateway_server/api/demo/** requests route to Accounts Overview Demo
    accounts_overview: 
      path: /demo/**
      serviceId: accounts-overview-ui
    # api_gateway_server/api/choreographer/** requests route to API service choreographer for backend processes
    service_choreographer: 
      path: /choreographer/**
      serviceId: api-service-choreographer